using Yoyoyopo5.ValueWrapper;

namespace TwitchySharp;

/// <summary>
/// An id representing a specific Twitch EventSub subscription type name.
/// </summary>
/// <param name="Value">The string value of the id.</param>
[Wrapper<string>]
public readonly partial record struct EventSubSubscriptionTypeName(string Value)
{
    /// <inheritdoc cref="EventSubSubscriptionType.AutomodMessageHold"/>
    public static EventSubSubscriptionTypeName AutomodMessageHold { get; } = new("automod.message.hold");
    /// <inheritdoc cref="EventSubSubscriptionType.AutomodMessageUpdate"/>
    public static EventSubSubscriptionTypeName AutomodMessageUpdate { get; } = new("automod.message.update");
    /// <inheritdoc cref="EventSubSubscriptionType.AutomodSettingsUpdate"/>
    public static EventSubSubscriptionTypeName AutomodSettingsUpdate { get; } = new("automod.settings.update");
    /// <inheritdoc cref="EventSubSubscriptionType.AutomodTermsUpdate"/>
    public static EventSubSubscriptionTypeName AutomodTermsUpdate { get; } = new("automod.terms.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelBitsUse"/>
    public static EventSubSubscriptionTypeName ChannelBitsUse { get; } = new("channel.bits.use");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelUpdate"/>
    public static EventSubSubscriptionTypeName ChannelUpdate { get; } = new("channel.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelFollow"/>
    public static EventSubSubscriptionTypeName ChannelFollow { get; } = new("channel.follow");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelAdBreakBegin"/>
    public static EventSubSubscriptionTypeName ChannelAdBreakBegin { get; } = new("channel.ad_break.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatClear"/>
    public static EventSubSubscriptionTypeName ChannelChatClear { get; } = new("channel.chat.clear");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatClearUserMessages"/>
    public static EventSubSubscriptionTypeName ChannelChatClearUserMessages { get; } = new("channel.chat.clear_user_messages");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatMessage"/>
    public static EventSubSubscriptionTypeName ChannelChatMessage { get; } = new("channel.chat.message");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatMessageDelete"/>
    public static EventSubSubscriptionTypeName ChannelChatMessageDelete { get; } = new("channel.chat.message_delete");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatNotification"/>
    public static EventSubSubscriptionTypeName ChannelChatNotification { get; } = new("channel.chat.notification");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatSettingsUpdate"/>
    public static EventSubSubscriptionTypeName ChannelChatSettingsUpdate { get; } = new("channel.chat_settings.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatUserMessageHold"/>
    public static EventSubSubscriptionTypeName ChannelChatUserMessageHold { get; } = new("channel.chat.user_message_hold");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelChatUserMessageUpdate"/>
    public static EventSubSubscriptionTypeName ChannelChatUserMessageUpdate { get; } = new("channel.chat.user_message_update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSharedChatSessionBegin"/>
    public static EventSubSubscriptionTypeName ChannelSharedChatSessionBegin { get; } = new("channel.shared_chat.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSharedChatSessionUpdate"/>
    public static EventSubSubscriptionTypeName ChannelSharedChatSessionUpdate { get; } = new("channel.shared_chat.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSharedChatSessionEnd"/>
    public static EventSubSubscriptionTypeName ChannelSharedChatSessionEnd { get; } = new("channel.shared_chat.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSubscribe"/>
    public static EventSubSubscriptionTypeName ChannelSubscribe { get; } = new("channel.subscribe");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSubscriptionEnd"/>
    public static EventSubSubscriptionTypeName ChannelSubscriptionEnd { get; } = new("channel.subscription.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSubscriptionGift"/>
    public static EventSubSubscriptionTypeName ChannelSubscriptionGift { get; } = new("channel.subscription.gift");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSubscriptionMessage"/>
    public static EventSubSubscriptionTypeName ChannelSubscriptionMessage { get; } = new("channel.subscription.message");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelCheer"/>
    public static EventSubSubscriptionTypeName ChannelCheer { get; } = new("channel.cheer");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelRaid"/>
    public static EventSubSubscriptionTypeName ChannelRaid { get; } = new("channel.raid");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelBan"/>
    public static EventSubSubscriptionTypeName ChannelBan { get; } = new("channel.ban");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelUnban"/>
    public static EventSubSubscriptionTypeName ChannelUnban { get; } = new("channel.unban");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelUnbanRequestCreate"/>
    public static EventSubSubscriptionTypeName ChannelUnbanRequestCreate { get; } = new("channel.unban_request.create");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelUnbanRequestResolve"/>
    public static EventSubSubscriptionTypeName ChannelUnbanRequestResolve { get; } = new("channel.unban_request.resolve");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelModerate"/>
    public static EventSubSubscriptionTypeName ChannelModerate { get; } = new("channel.moderate");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelModeratorAdd"/>
    public static EventSubSubscriptionTypeName ChannelModeratorAdd { get; } = new("channel.moderator.add");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelModeratorRemove"/>
    public static EventSubSubscriptionTypeName ChannelModeratorRemove { get; } = new("channel.moderator.remove");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelGuestStarSessionBegin"/>
    public static EventSubSubscriptionTypeName ChannelGuestStarSessionBegin { get; } = new("channel.guest_star_session.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelGuestStarSessionEnd"/>
    public static EventSubSubscriptionTypeName ChannelGuestStarSessionEnd { get; } = new("channel.guest_star_session.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelGuestStarGuestUpdate"/>
    public static EventSubSubscriptionTypeName ChannelGuestStarGuestUpdate { get; } = new("channel.guest_star_guest.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelGuestStarSettingsUpdate"/>
    public static EventSubSubscriptionTypeName ChannelGuestStarSettingsUpdate { get; } = new("channel.guest_star_settings.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPointsAutomaticRewardRedemptionAdd"/>
    public static EventSubSubscriptionTypeName ChannelPointsAutomaticRewardRedemptionAdd { get; } = new("channel.channel_points_automatic_reward_redemption.add");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPointsCustomRewardAdd"/>
    public static EventSubSubscriptionTypeName ChannelPointsCustomRewardAdd { get; } = new("channel.channel_points_custom_reward.add");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPointsCustomRewardUpdate"/>
    public static EventSubSubscriptionTypeName ChannelPointsCustomRewardUpdate { get; } = new("channel.channel_points_custom_reward.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPointsCustomRewardRemove"/>
    public static EventSubSubscriptionTypeName ChannelPointsCustomRewardRemove { get; } = new("channel.channel_points_custom_reward.remove");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPointsCustomRewardRedemptionAdd"/>
    public static EventSubSubscriptionTypeName ChannelPointsCustomRewardRedemptionAdd { get; } = new("channel.channel_points_custom_reward_redemption.add");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPointsCustomRewardRedemptionUpdate"/>
    public static EventSubSubscriptionTypeName ChannelPointsCustomRewardRedemptionUpdate { get; } = new("channel.channel_points_custom_reward_redemption.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPollBegin"/>
    public static EventSubSubscriptionTypeName ChannelPollBegin { get; } = new("channel.poll.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPollProgress"/>
    public static EventSubSubscriptionTypeName ChannelPollProgress { get; } = new("channel.poll.progress");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPollEnd"/>
    public static EventSubSubscriptionTypeName ChannelPollEnd { get; } = new("channel.poll.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPredictionBegin"/>
    public static EventSubSubscriptionTypeName ChannelPredictionBegin { get; } = new("channel.prediction.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPredictionProgress"/>
    public static EventSubSubscriptionTypeName ChannelPredictionProgress { get; } = new("channel.prediction.progress");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPredictionLock"/>
    public static EventSubSubscriptionTypeName ChannelPredictionLock { get; } = new("channel.prediction.lock");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelPredictionEnd"/>
    public static EventSubSubscriptionTypeName ChannelPredictionEnd { get; } = new("channel.prediction.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSuspiciousUserMessage"/>
    public static EventSubSubscriptionTypeName ChannelSuspiciousUserMessage { get; } = new("channel.suspicious_user.message");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelSuspiciousUserUpdate"/>
    public static EventSubSubscriptionTypeName ChannelSuspiciousUserUpdate { get; } = new("channel.suspicious_user.update");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelVipAdd"/>
    public static EventSubSubscriptionTypeName ChannelVipAdd { get; } = new("channel.vip.add");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelVipRemove"/>
    public static EventSubSubscriptionTypeName ChannelVipRemove { get; } = new("channel.vip.remove");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelWarningAcknowledgement"/>
    public static EventSubSubscriptionTypeName ChannelWarningAcknowledgement { get; } = new("channel.warning.acknowledge");
    /// <inheritdoc cref="EventSubSubscriptionType.ChannelWarningSend"/>
    public static EventSubSubscriptionTypeName ChannelWarningSend { get; } = new("channel.warning.send");
    /// <inheritdoc cref="EventSubSubscriptionType.CharityDonation"/>
    public static EventSubSubscriptionTypeName CharityDonation { get; } = new("channel.charity_campaign.donate");
    /// <inheritdoc cref="EventSubSubscriptionType.CharityCampaignStart"/>
    public static EventSubSubscriptionTypeName CharityCampaignStart { get; } = new("channel.charity_campaign.start");
    /// <inheritdoc cref="EventSubSubscriptionType.CharityCampaignProgress"/>
    public static EventSubSubscriptionTypeName CharityCampaignProgress { get; } = new("channel.charity_campaign.progress");
    /// <inheritdoc cref="EventSubSubscriptionType.CharityCampaignStop"/>
    public static EventSubSubscriptionTypeName CharityCampaignStop { get; } = new("channel.charity_campaign.stop");
    /// <inheritdoc cref="EventSubSubscriptionType.ConduitShardDisabled"/>
    public static EventSubSubscriptionTypeName ConduitShardDisabled { get; } = new("conduit.shard.disabled");
    /// <inheritdoc cref="EventSubSubscriptionType.DropEntitlementGrant"/>
    public static EventSubSubscriptionTypeName DropEntitlementGrant { get; } = new("drop.entitlement.grant");
    /// <inheritdoc cref="EventSubSubscriptionType.ExtensionBitsTransactionCreate"/>
    public static EventSubSubscriptionTypeName ExtensionBitsTransactionCreate { get; } = new("extension.bits_transaction.create");
    /// <inheritdoc cref="EventSubSubscriptionType.GoalBegin"/>
    public static EventSubSubscriptionTypeName GoalBegin { get; } = new("channel.goal.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.GoalProgress"/>
    public static EventSubSubscriptionTypeName GoalProgress { get; } = new("channel.goal.progress");
    /// <inheritdoc cref="EventSubSubscriptionType.GoalEnd"/>
    public static EventSubSubscriptionTypeName GoalEnd { get; } = new("channel.goal.end");
    /// <inheritdoc cref="EventSubSubscriptionType.HypeTrainBegin"/>
    public static EventSubSubscriptionTypeName HypeTrainBegin { get; } = new("channel.hype_train.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.HypeTrainProgress"/>
    public static EventSubSubscriptionTypeName HypeTrainProgress { get; } = new("channel.hype_train.progress");
    /// <inheritdoc cref="EventSubSubscriptionType.HypeTrainEnd"/>
    public static EventSubSubscriptionTypeName HypeTrainEnd { get; } = new("channel.hype_train.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ShieldModeBegin"/>
    public static EventSubSubscriptionTypeName ShieldModeBegin { get; } = new("channel.shield_mode.begin");
    /// <inheritdoc cref="EventSubSubscriptionType.ShieldModeEnd"/>
    public static EventSubSubscriptionTypeName ShieldModeEnd { get; } = new("channel.shield_mode.end");
    /// <inheritdoc cref="EventSubSubscriptionType.ShoutoutCreate"/>
    public static EventSubSubscriptionTypeName ShoutoutCreate { get; } = new("channel.shoutout.create");
    /// <inheritdoc cref="EventSubSubscriptionType.ShoutoutReceived"/>
    public static EventSubSubscriptionTypeName ShoutoutReceived { get; } = new("channel.shoutout.receive");
    /// <inheritdoc cref="EventSubSubscriptionType.StreamOnline"/>
    public static EventSubSubscriptionTypeName StreamOnline { get; } = new("stream.online");
    /// <inheritdoc cref="EventSubSubscriptionType.StreamOffline"/>
    public static EventSubSubscriptionTypeName StreamOffline { get; } = new("stream.offline");
    /// <inheritdoc cref="EventSubSubscriptionType.UserAuthorizationGrant"/>
    public static EventSubSubscriptionTypeName UserAuthorizationGrant { get; } = new("user.authorization.grant");
    /// <inheritdoc cref="EventSubSubscriptionType.UserAuthorizationRevoke"/>
    public static EventSubSubscriptionTypeName UserAuthorizationRevoke { get; } = new("user.authorization.revoke");
    /// <inheritdoc cref="EventSubSubscriptionType.UserUpdate"/>
    public static EventSubSubscriptionTypeName UserUpdate { get; } = new("user.update");
    /// <inheritdoc cref="EventSubSubscriptionType.WhisperReceived"/>
    public static EventSubSubscriptionTypeName WhisperReceived { get; } = new("user.whisper.message");
}
