using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;

namespace TwitchySharp.Helpers.Generators;

public static class ValueWrapperConstants
{
    public const string FULLY_QUALIFIED_WRAPPER_INTERFACE_NAME = "TwitchySharp.Helpers.IWrapValue`1";
    public const string WRAPPER_INTERFACE_NAME = "IWrapValue";
    public const string JSON_CONVERTER_ATTRIBUTE_NAME = "System.Text.Json.Serialization.JsonConverterAttribute";
}

internal record ValueWrapperGeneratorState
{
    public INamedTypeSymbol? WrapperTypeSymbol { get; init; }
    public INamedTypeSymbol? InterfaceTypeSymbol { get; init; }
    public INamedTypeSymbol? JsonConverterAttributeSymbol { get; init; }
}

[Generator]
public class ValueWrapperMethodGenerator : IIncrementalGenerator
{
# pragma warning disable RS2008 // We can work on this later if we want a shipped ruleset.
    private static readonly DiagnosticDescriptor PartialModifierRequiredWarning = new(
        id: "VWG001",
        title: "The struct must be partial",
        messageFormat: "Make '{0}' partial to enable generation of ToString and implicit operator methods",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true
        );
# pragma warning restore RS2008

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<INamedTypeSymbol?> wrapperInterfaceProvider = context.CompilationProvider
            .Select(static (compilation, ct) => compilation.GetTypeByMetadataName(ValueWrapperConstants.FULLY_QUALIFIED_WRAPPER_INTERFACE_NAME));

        IncrementalValueProvider<INamedTypeSymbol?> jsonConverterAttributeProvider = context.CompilationProvider
            .Select(static (compilation, ct) => compilation.GetTypeByMetadataName(ValueWrapperConstants.JSON_CONVERTER_ATTRIBUTE_NAME));

        IncrementalValuesProvider<ValueWrapperDefinition?> provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: GeneratorExtensions.IsLikelyWrapperDeclaration,
            transform: GeneratorExtensions.GetValueWrapperSymbolOrDefault
            )
            .Where(m => m is not null)
            .Select(static (ctx, ct) => new ValueWrapperGeneratorState()
            {
                WrapperTypeSymbol = ctx
            })
            .Combine(wrapperInterfaceProvider)
            .Select(static (ctx, ct) => ctx.Left with
            {
                InterfaceTypeSymbol = ctx.Right
            })
            .Combine(jsonConverterAttributeProvider)
            .Select(static (ctx, ct) => ctx.Left with
            {
                JsonConverterAttributeSymbol = ctx.Right
            })
            .SelectValueWrapper();

        context.RegisterSourceOutput(provider, (ctx, w) =>
        {
            if (w is not ValueWrapperDefinition wrapper)
                return;

            if (wrapper.ImplicitConversionOperator is not null
                && wrapper.ToStringOverride is not null
                && (wrapper.ValueProperty is not null || wrapper.WrappedValueParameterName == "Value"))
                return;

            if (!wrapper.IsPartial)
            {
                if (wrapper.Location.IsInSource)
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        PartialModifierRequiredWarning,
                        wrapper.Location,
                        wrapper.TypeName
                        ));
                return;
            }

            foreach (ClassDefiniton parent in wrapper.Parents)
            {
                if (!parent.IsPartial)
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        PartialModifierRequiredWarning,
                        parent.Location,
                        parent.TypeName
                        ));
            }

            using StringWriter sw = new();
            using IndentedTextWriter sourceWriter = new(sw, "    ");

            sourceWriter.WriteLine("// <auto-generated/>");
            sourceWriter.WriteLine("#nullable enable");
            sourceWriter.WriteLine();
            sourceWriter.WriteLine($"namespace {wrapper.Namespace};");
            foreach (ClassDefiniton parent in wrapper.Parents)
            {
                sourceWriter.WriteLine(parent.ExtendPartial());
                sourceWriter.WriteLine("{");
                sourceWriter.Indent++;
            }
            sourceWriter.WriteLine(wrapper.ExtendPartial());
            sourceWriter.WriteLine("{");
            sourceWriter.Indent++;
            if (wrapper.ValueProperty is null && wrapper.WrappedValueParameterName != "Value")
                sourceWriter.WriteLine(wrapper.WrappedValueParameterName switch
                {
                    string parameterName when !string.IsNullOrEmpty(parameterName) => $$"""public {{wrapper.WrappedType.ToDisplayString()}} Value { get; init; } = {{parameterName}};""",
                    _ => $$"""public required {{wrapper.WrappedType.ToDisplayString()}} Value { get; init; }"""
                });
            if (wrapper.ImplicitConversionOperator is null)
                sourceWriter.WriteLine($"public static implicit operator {wrapper.WrappedType.ToDisplayString()}({wrapper.TypeName} wrapper) => wrapper.Value;");
            if (wrapper.ToStringOverride is null)
                sourceWriter.WriteLine("public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;");
            sourceWriter.Indent--;
            sourceWriter.WriteLine("}");
            foreach (ClassDefiniton _ in wrapper.Parents)
            {
                sourceWriter.Indent--;
                sourceWriter.WriteLine("}");
            }

            ctx.AddSource($"{wrapper.TypeName}_ConversionMethods.g.cs", sw.ToString());
        });
    }
}

internal record ValueWrapperDefinition(INamedTypeSymbol TypeSymbol, ITypeSymbol WrappedType, INamedTypeSymbol? JsonConverterAttributeType): ClassDefiniton(TypeSymbol)
{
    public string? WrappedValueParameterName => Syntax.FirstOrDefault().ParameterList switch
    {
        { } parameterList when parameterList.Parameters.Count > 0
            => TypeSymbol.InstanceConstructors
                .FirstOrDefault(c => c.Locations.Any(l => l.SourceSpan.Contains(parameterList.Span))) switch
            {
                IMethodSymbol primaryConstructor => primaryConstructor.Parameters.FirstOrDefault(p => SymbolEqualityComparer.Default.Equals(p.Type, WrappedType))?.Name,
                _ => null
            },
        _ => null
    };
    public IPropertySymbol? ValueProperty { get; } = TypeSymbol.GetMembers("Value")
        .OfType<IPropertySymbol>()
        .FirstOrDefault(p => SymbolEqualityComparer.Default.Equals(p.Type, WrappedType));
    public IMethodSymbol? ImplicitConversionOperator { get; } = TypeSymbol.GetMembers()
        .OfType<IMethodSymbol>()
        .FirstOrDefault(m => m.MethodKind == MethodKind.Conversion
            && m.Name == "op_Implicit"
            && SymbolEqualityComparer.Default.Equals(m.ReturnType, WrappedType));
    public IMethodSymbol? ToStringOverride { get; } = TypeSymbol.GetMembers("ToString")
        .OfType<IMethodSymbol>()
        .FirstOrDefault(m => m.Parameters.Length == 0 && m.IsOverride);
    public AttributeData? JsonConverterAttribute { get; } = TypeSymbol.GetAttributes()
        .FirstOrDefault(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, JsonConverterAttributeType));
}

internal static class GeneratorExtensions
{
    public static bool IsLikelyWrapperDeclaration(this SyntaxNode node, CancellationToken ct)
        => node is TypeDeclarationSyntax { BaseList: not null } declaration
            && declaration.BaseList.Types.Any(static t => t.ToString().Contains(ValueWrapperConstants.WRAPPER_INTERFACE_NAME));

    public static INamedTypeSymbol? GetValueWrapperSymbolOrDefault(this GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (context.Node is not TypeDeclarationSyntax typeDeclaration)
            return null;

        if (context.SemanticModel.GetDeclaredSymbol(typeDeclaration, ct) is not INamedTypeSymbol { TypeKind: TypeKind.Struct } symbol)
            return null;

        return symbol;
    }

    public static IncrementalValuesProvider<ValueWrapperDefinition?> SelectValueWrapper(this IncrementalValuesProvider<ValueWrapperGeneratorState> provider)
        => provider.Select((ctx, ct) =>
        {
            if (ctx.WrapperTypeSymbol is null || ctx.InterfaceTypeSymbol is null)
                return null;

            return ctx.WrapperTypeSymbol.ToValueWrapperOrDefault(ctx.InterfaceTypeSymbol, ctx.JsonConverterAttributeSymbol, ct);
        });

    private static ValueWrapperDefinition? ToValueWrapperOrDefault(this INamedTypeSymbol wrapperDeclaration, INamedTypeSymbol interfaceDeclaration, INamedTypeSymbol? jsonConverterAttributeTypeSymbol, CancellationToken ct)
    {
        if (wrapperDeclaration.AllInterfaces.FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.ConstructedFrom, interfaceDeclaration)) is not INamedTypeSymbol interfaceSymbol)
            return null;

        if (!interfaceSymbol.IsGenericType || interfaceSymbol.TypeArguments.Length == 0)
            return null;

        if (interfaceSymbol.TypeArguments.FirstOrDefault() is not ITypeSymbol wrappedValueType)
            return null;

        IEnumerable<TypeDeclarationSyntax> wrapperDeclarationSyntaxNodes = wrapperDeclaration.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax(ct))
                .OfType<TypeDeclarationSyntax>();

        return new ValueWrapperDefinition(wrapperDeclaration, wrappedValueType, jsonConverterAttributeTypeSymbol);
    }

    public static IReadOnlyList<INamedTypeSymbol> GetContainingTypes(this INamedTypeSymbol symbol)
    {
        List<INamedTypeSymbol> containingTypes = [];
        INamedTypeSymbol? current = symbol.ContainingType;

        while (current is not null)
        {
            containingTypes.Add(current);
            current = current.ContainingType;
        }

        return containingTypes;
    }

    public static string ToCodeString(this Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => string.Empty
        };

    public static string ToCodeString(this TypeKind typeKind)
        => typeKind switch
        {
            TypeKind.Struct or TypeKind.Structure => "struct",
            TypeKind.Class => "class",
            TypeKind.Interface => "interface",
            _ => string.Empty
        };
}