<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LangVer>latest</LangVer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/TwitchySharp.Core/TwitchySharp.Core.csproj" />
  </ItemGroup>

</Project>
