using System;
using System.Text.Json.Serialization;
using TwitchySharp.Api.Authorization;
using TwitchySharp.Helpers;

namespace TwitchySharp.Api;

/// <summary>
/// A Twitch API bearer access token.
/// </summary>
/// <remarks>
/// Use <see cref="AppAccessToken"/>, <see cref="ExtensionJsonWebToken"/>, or <see cref="UserAccessToken"/>, depending on the endpoint.
/// </remarks>
public interface IAccessToken
{
    /// <summary>
    /// The string value of the access token.
    /// </summary>
    string Value { get; }
}

/// <summary>
/// A Twitch app access token.
/// </summary>
/// <remarks>
/// APIs that don’t require the user’s permission to access resources use app access tokens.
/// <br/>
/// See <see href="https://dev.twitch.tv/docs/authentication/#app-access-tokens">App Access Tokens</see> for more information.
/// </remarks>
[JsonConverter(typeof(WrapperJsonConverter<AppAccessToken, string>))]
public readonly record struct AppAccessToken(string Value) : IAccessToken, IWrapValue<string>;

/// <summary>
/// A Twitch user access token.
/// </summary>
/// <remarks>
/// APIs that require the user’s permission to access resources use user access tokens. Can include various <see cref="Scope"/>s.
/// <br/>
/// See <see href="https://dev.twitch.tv/docs/authentication/#user-access-tokens">User Access Tokens</see> for more information.
/// </remarks>
[JsonConverter(typeof(WrapperJsonConverter<UserAccessToken, string>))]
public readonly record struct UserAccessToken(string Value) : IAccessToken, IWrapValue<string>;

/// <summary>
/// A Twitch extension JSON web token generated by an EBS.
/// </summary>
/// <remarks>
/// Some extension APIs require EBS-generated JWTs. The <see cref="ExtensionJwtPayload"/> record contains 
/// a <see cref="ExtensionJwtPayload.Sign(string, System.Text.Json.JsonSerializerOptions?)"/> method you can use to create a valid JWT.
/// <br/>
/// See <see href="https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt">Signing the JWT</see> for more information.
/// </remarks>
[JsonConverter(typeof(WrapperJsonConverter<UserAccessToken, string>))]
public readonly record struct ExtensionJsonWebToken(string Value) : IAccessToken, IWrapValue<string>;
