<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UserSecretsId>f919df22-ff55-4c9a-b116-3e9e299a8a5a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.1" />
	<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwitchySharp.Api\TwitchySharp.Api.csproj" />
    <ProjectReference Include="..\TwitchySharp.EventSub.Websocket.Clients.WebsocketClient\TwitchySharp.EventSub.Websocket.Clients.WebsocketClient.csproj" />
    <ProjectReference Include="..\TwitchySharp.EventSub.Websocket\TwitchySharp.EventSub.Websocket.csproj" />
    <ProjectReference Include="..\TwitchySharp.EventSub\TwitchySharp.EventSub.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
