<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TwitchySharp.EventSub/TwitchySharp.EventSub.csproj" />
    <ProjectReference Include="../../TwitchySharp.Helpers/TwitchySharp.Helpers.csproj" />
  </ItemGroup>

</Project>
