<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwitchySharp.Helpers.Generators\TwitchySharp.Helpers.Generators.csproj" 
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      />
    <ProjectReference Include="..\TwitchySharp.Helpers.Analyzers\TwitchySharp.Helpers.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      />
    <Analyzer Include="..\TwitchySharp.Helpers.Generators\bin\$(Configuration)\netstandard2.0\Scriban.dll" />
    <ProjectReference Include="..\TwitchySharp.Helpers\TwitchySharp.Helpers.csproj" />
  </ItemGroup>

</Project>
