<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
      <LangVersion>latest</LangVersion>
      <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\"></None>
  </ItemGroup>

</Project>
