using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace TwitchySharp.Helpers.Generators.Tests;

public class Test_ValueWrapperGenerator
{
    private const string FAKE_CONVERTER = """
        using System;
        using System.Text.Json;
        using System.Text.Json.Serialization;

        namespace TestNamespace;
        public class FakeConverter<T> : JsonConverter<T>
        {
            public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                throw new NotImplementedException();
            }
            public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
            {
                throw new NotImplementedException();
            }
        }

        """;

    private const string EXPECTED_FILE_PATH_SUFFIX = "_Wrapper.g.cs";
    private readonly static SourceGeneratorTestCase[] _testCases =
    [
        new SourceGeneratorTestCase()
        {
            Name = "AddsAllMembersToEmptyType",
            Input = """
            using TwitchySharp.Helpers;
            namespace TestNamespace;
            [Wrapper<string>]
            public readonly partial record struct AddsAllMembersToEmptyType;
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::TwitchySharp.Helpers.WrapperJsonConverter<AddsAllMembersToEmptyType, global::System.String>))]
            public readonly partial record struct AddsAllMembersToEmptyType
                : global::TwitchySharp.Helpers.IWrapValue<global::System.String, AddsAllMembersToEmptyType>
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(AddsAllMembersToEmptyType wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value != null ? Value.ToString() : global::System.String.Empty;
                static AddsAllMembersToEmptyType global::TwitchySharp.Helpers.IWrapValue<global::System.String, AddsAllMembersToEmptyType>.Create(global::System.String value) => new() { Value = value };
            }

            """,
            ExpectedOutputFilePath = $"AddsAllMembersToEmptyType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddsCreateMethodToFullType",
            Input = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;
            namespace TestNamespace;
            [Wrapper<string>]
            [JsonConverter(typeof(FakeConverter<string>))]
            public readonly partial record struct AddsCreateMethodToFullType
            {
                public required string Value { get; init; }
                public override string ToString() => Value;
                public static implicit operator string(AddsCreateMethodToFullType wrapper) => wrapper.Value;
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public readonly partial record struct AddsCreateMethodToFullType
                : global::TwitchySharp.Helpers.IWrapValue<global::System.String, AddsCreateMethodToFullType>
            {
                static AddsCreateMethodToFullType global::TwitchySharp.Helpers.IWrapValue<global::System.String, AddsCreateMethodToFullType>.Create(global::System.String value) => new() { Value = value };
            }

            """,
            ExpectedOutputFilePath = $"AddsCreateMethodToFullType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingNonPartialRecord",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<string>]
            public record SkipsGeneratingNonPartialRecord;
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "GeneratesNestedWrapperType",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            public partial class ContainerOne
            {
                public partial class ContainerTwo
                {
                    [Wrapper<int>]
                    public partial class GeneratesNestedWrapperType { }
                }
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial class ContainerOne
            {
                public partial class ContainerTwo
                {
                    [global::System.Text.Json.Serialization.JsonConverter(typeof(global::TwitchySharp.Helpers.WrapperJsonConverter<GeneratesNestedWrapperType, global::System.Int32>))]
                    public partial class GeneratesNestedWrapperType
                        : global::TwitchySharp.Helpers.IWrapValue<global::System.Int32, GeneratesNestedWrapperType>
                    {
                        public required global::System.Int32 Value { get; init; }
                        public static implicit operator global::System.Int32(GeneratesNestedWrapperType wrapper) => wrapper.Value;
                        public override global::System.String ToString() => Value != null ? Value.ToString() : global::System.String.Empty;
                        static GeneratesNestedWrapperType global::TwitchySharp.Helpers.IWrapValue<global::System.Int32, GeneratesNestedWrapperType>.Create(global::System.Int32 value) => new() { Value = value };
                    }
                }
            }
            
            """,
            ExpectedOutputFilePath = $"GeneratesNestedWrapperType{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsValuePropertyOnRecordWithPrimaryConstructor",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<double>]
            public partial record SkipsValuePropertyOnRecordWithPrimaryConstructor(double Value);
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            [global::System.Text.Json.Serialization.JsonConverter(typeof(global::TwitchySharp.Helpers.WrapperJsonConverter<SkipsValuePropertyOnRecordWithPrimaryConstructor, global::System.Double>))]
            public partial record class SkipsValuePropertyOnRecordWithPrimaryConstructor
                : global::TwitchySharp.Helpers.IWrapValue<global::System.Double, SkipsValuePropertyOnRecordWithPrimaryConstructor>
            {
                public static implicit operator global::System.Double(SkipsValuePropertyOnRecordWithPrimaryConstructor wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value != null ? Value.ToString() : global::System.String.Empty;
                static SkipsValuePropertyOnRecordWithPrimaryConstructor global::TwitchySharp.Helpers.IWrapValue<global::System.Double, SkipsValuePropertyOnRecordWithPrimaryConstructor>.Create(global::System.Double value) => new(value);
            }
            
            """,
            ExpectedOutputFilePath = $"SkipsValuePropertyOnRecordWithPrimaryConstructor{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingRecordWithWronglyTypedPrimaryConstructor",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<string>]
            public partial record SkipsGeneratingRecordWithWronglyTypedPrimaryConstructor(int Value);
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsGeneratingClassWithWronglyTypedValueProperty",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<string>]
            public partial class SkipsGeneratingClassWithWronglyTypedValueProperty
            {
                public int Value { get; init; }
            }
            """,
            ExpectedOutput = null,
            ExpectedOutputFilePath = null
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsAddingJsonConverterWithNonValueRequiredProps",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<string>]
            public partial record SkipsAddingJsonConverterWithNonValueRequiredProps
            {
                public required int Amount { get; init; }
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial record class SkipsAddingJsonConverterWithNonValueRequiredProps // also skips interface
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(SkipsAddingJsonConverterWithNonValueRequiredProps wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value != null ? Value.ToString() : global::System.String.Empty;
            }
            """,
            ExpectedOutputFilePath = $"SkipsAddingJsonConverterWithNonValueRequiredProps{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "SkipsAddingJsonConverterOnRecordWithNonValuePrimaryConstructorArgs",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<string>]
            public partial record SkipsAddingJsonConverterOnRecordWithNonValuePrimaryConstructorArgs(int Amount);
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial record class SkipsAddingJsonConverterWithNonValueRequiredProps // also skips interface
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(SkipsAddingJsonConverterWithNonValueRequiredProps wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value != null ? Value.ToString() : global::System.String.Empty;
            }
            """,
            ExpectedOutputFilePath = $"SkipsAddingJsonConverterWithNonValueRequiredProps{EXPECTED_FILE_PATH_SUFFIX}"
        },
        new SourceGeneratorTestCase()
        {
            Name = "AddsJsonConverterWithNonValueRequiredPropsAndSuitableStaticCreateMethod",
            Input = """
            namespace TestNamespace;
            using TwitchySharp.Helpers;
            [Wrapper<string>]
            public partial record AddsJsonConverterWithNonValueRequiredPropsAndSuitableStaticCreateMethod
            {
                public required int Amount { get; init; }
                public static SkipsAddingJsonConverterWithNonValueRequiredProps Create(string amount)
                    => new() { Amount = int.Parse(amount) }
            }
            """,
            ExpectedOutput = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial record class AddsJsonConverterWithNonValueRequiredPropsAndSuitableStaticCreateMethod
                : IWrapValue<global::System.String, AddsJsonConverterWithNonValueRequiredPropsAndSuitableStaticCreateMethod>
            {
                public required global::System.String Value { get; init; }
                public static implicit operator global::System.String(SkipsAddingJsonConverterWithNonValueRequiredProps wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value != null ? Value.ToString() : global::System.String.Empty;
                static IWrapValue<global::System.String, AddsJsonConverterWithNonValueRequiredPropsAndSuitableStaticCreateMethod>.Create(global::System.String value) => Create(value);
            }
            """,
            ExpectedOutputFilePath = $"AddsJsonConverterWithNonValueRequiredPropsAndSuitableStaticCreateMethod{EXPECTED_FILE_PATH_SUFFIX}"
        }
    ];
    public static TheoryData<TestCaseWrapper<SourceGeneratorTestCase>> TestCases
        => [.. _testCases.Select(t => new TestCaseWrapper<SourceGeneratorTestCase>(t))];

    private static CSharpSourceGeneratorTest<ValueWrapperGenerator, DefaultVerifier> CreateGeneratorTest()
    {
        CSharpSourceGeneratorTest<ValueWrapperGenerator, DefaultVerifier> test = new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80
        };
        test.TestState.AdditionalReferences.Add(typeof(WrapperAttribute<>).Assembly);
        test.TestState.Sources.Add(FAKE_CONVERTER);
        return test;
    }

    [Theory]
    [MemberData(nameof(TestCases))]
    public async Task Generator(TestCaseWrapper<SourceGeneratorTestCase> @case)
        => await @case.TestCase.Register(CreateGeneratorTest()).RunAsync(TestContext.Current.CancellationToken);
}
