using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace TwitchySharp.Helpers.Generators.Tests;

public class Test_ValueWrapperMethodGenerator
{
    private static CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> CreateGeneratorTest(string input)
    {
        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = new()
        {
            TestCode = input,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80
        };
        test.TestState.AdditionalReferences.Add(typeof(IWrapValue<>).Assembly);
        return test;
    }

    [Fact]
    public async Task Generator_AddsValueProperty_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public readonly partial record struct TestWrapper : IWrapValue<string>
            {
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override string ToString() => Value.ToString();
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;
            public readonly partial record struct TestWrapper
            {
                public required string Value { get; init; }
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsImplicitOperator_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial record struct TestWrapper(string Value) : IWrapValue<string>
            {
                public override string ToString() => Value.ToString();
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;
            public partial record struct TestWrapper
            {
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsToStringOverride_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;
            public partial struct TestWrapper
            {
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsAllMembers_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial struct TestWrapper : IWrapValue<string>;
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;
            public partial struct TestWrapper
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsNothing_ToWrapperStructWithGeneratedMembers()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override string ToString() => Value;
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsNothing_ToPartialWrapperClass()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial class TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsAllMembers_ToNestedWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test container type</summary>
            public partial class Container
            {
                /// <summary>Test type</summary>
                private partial struct TestWrapper : IWrapValue<string>;
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;
            public partial class Container
            {
                private partial struct TestWrapper
                {
                    public required string Value { get; init; }
                    public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                    public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
                }
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_Warns_WhenStructIsNotPartial()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public struct {|#0:TestWrapper|} : IWrapValue<string>
            {
                public required string Value { get; init; }
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.ExpectedDiagnostics.Add(DiagnosticResult.CompilerWarning("VWG001").WithLocation(0));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_DoesNotWarn_WhenStructIsNotPartialWithGeneratedMembers()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public override string ToString() => Value;
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_DoesNotWarn_WhenWrapperClassIsNonPartial()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public record TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_Warns_WhenContainingTypeIsNotPartial()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            namespace TestNamespace;
            /// <summary>Test type</summary>
            public class {|#0:Container|}
            {
                public struct {|#1:TestWrapper|} : IWrapValue<string>
                {
                    public required string Value { get; init; }
                }
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.ExpectedDiagnostics.Add(DiagnosticResult.CompilerWarning("VWG001").WithLocation(1));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }
}
