using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace TwitchySharp.Helpers.Generators.Tests;

public class Test_ValueWrapperMethodGenerator
{
    private const string FAKE_CONVERTER = """
        using System;
        using System.Text.Json;
        using System.Text.Json.Serialization;

        namespace TestNamespace;
        public class FakeConverter<T> : JsonConverter<T>
        {
            public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                throw new NotImplementedException();
            }
            public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
            {
                throw new NotImplementedException();
            }
        }

        """;

    private static CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> CreateGeneratorTest(string input)
    {
        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = new()
        {
            TestCode = input,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80
        };
        test.TestState.AdditionalReferences.Add(typeof(IWrapValue<>).Assembly);
        test.TestState.Sources.Add(FAKE_CONVERTER);
        return test;
    }

    [Fact]
    public async Task Generator_AddsValueProperty_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = $$"""
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public readonly partial record struct TestWrapper : IWrapValue<string>
            {
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override string ToString() => Value.ToString();
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public readonly partial record struct TestWrapper
            {
                public required string Value { get; init; }
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsImplicitOperator_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public partial record struct TestWrapper(string Value) : IWrapValue<string>
            {
                public override string ToString() => Value.ToString();
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial record struct TestWrapper
            {
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsToStringOverride_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public partial struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial struct TestWrapper
            {
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsAllMembers_ToPartialWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial struct TestWrapper : IWrapValue<string>;
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            [global::System.Text.Json.Serialization.JsonConverter(typeof(TestWrapperJsonConverter))]
            public partial struct TestWrapper
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
                private class TestWrapperJsonConverter : global::System.Text.Json.Serialization.JsonConverter<TestWrapper>
                {
                    public override TestWrapper Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                    {
                        if (global::System.Text.Json.JsonSerializer.Deserialize<string>(ref reader, options) is not string value)
                            return default;
                        return new TestWrapper { Value = value };
                    }
                    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, TestWrapper value, global::System.Text.Json.JsonSerializerOptions options)
                    {
                        global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
                    }
                }
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsNothing_ToWrapperStructWithGeneratedMembers()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public partial struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override string ToString() => Value;
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsAllMembers_ToNestedWrapperStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test top level container type</summary>
            public partial class Container
            {
                /// <summary>Test nested container type</summary>
                public partial class ContainerTwo
                {
                    /// <summary>Test type</summary>
                    private partial struct TestWrapper : IWrapValue<string>;
                }
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial class Container
            {
                public partial class ContainerTwo
                {
                    [global::System.Text.Json.Serialization.JsonConverter(typeof(TestWrapperJsonConverter))]
                    private partial struct TestWrapper
                    {
                        public required string Value { get; init; }
                        public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                        public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
                        private class TestWrapperJsonConverter : global::System.Text.Json.Serialization.JsonConverter<TestWrapper>
                        {
                            public override TestWrapper Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                            {
                                if (global::System.Text.Json.JsonSerializer.Deserialize<string>(ref reader, options) is not string value)
                                    return default;
                                return new TestWrapper { Value = value };
                            }
                            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, TestWrapper value, global::System.Text.Json.JsonSerializerOptions options)
                            {
                                global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
                            }
                        }
                    }
                }
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_Warns_WhenStructIsNotPartial()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            public struct {|#0:TestWrapper|} : IWrapValue<string>
            {
                public required string Value { get; init; }
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.ExpectedDiagnostics.Add(DiagnosticResult.CompilerWarning("VWG001").WithLocation(0));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_DoesNotWarn_WhenStructIsNotPartialWithGeneratedMembers()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public override string ToString() => Value;
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_Warns_WhenContainingTypeIsNotPartial()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            namespace TestNamespace;
            /// <summary>Test type</summary>
            public class {|#0:Container|}
            {
                public struct {|#1:TestWrapper|} : IWrapValue<string>
                {
                    public required string Value { get; init; }
                }
            }
            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.ExpectedDiagnostics.Add(DiagnosticResult.CompilerWarning("VWG001").WithLocation(1));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_Warns_WhenWrapperHasNonSettableValuePropertyAndNoConstructor()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial struct {|#0:TestWrapper|}() : IWrapValue<string>
            {
                public string Value { get; } = "test_value";
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial struct TestWrapper
            {
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));
        test.ExpectedDiagnostics.Add(DiagnosticResult.CompilerWarning("VWG002").WithLocation(0));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_DoesNotWarn_WhenWrapperHasNonSettableValuePropertyAndJsonConverterAttribute()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;
            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public partial struct {|#0:TestWrapper|}() : IWrapValue<string>
            {
                public string Value { get; } = "test_value";
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial struct TestWrapper
            {
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));
        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_AddsJsonConverterTypeAndAttribute_ToPartialStruct()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            namespace TestNamespace;
            /// <summary>Test type</summary>
            public partial struct TestWrapper : IWrapValue<string>
            {
                public required string Value { get; init; }
                public override string ToString() => Value;
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
            }
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable
            
            namespace TestNamespace;

            [global::System.Text.Json.Serialization.JsonConverter(typeof(TestWrapperJsonConverter))]
            public partial struct TestWrapper
            {
                private class TestWrapperJsonConverter : global::System.Text.Json.Serialization.JsonConverter<TestWrapper>
                {
                    public override TestWrapper Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                    {
                        if (global::System.Text.Json.JsonSerializer.Deserialize<string>(ref reader, options) is not string value)
                            return default;
                        return new TestWrapper { Value = value };
                    }
                    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, TestWrapper value, global::System.Text.Json.JsonSerializerOptions options)
                    {
                        global::System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
                    }
                }
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task Generator_DoesNotAddJsonConverterTypeAndAttribute_ToPartialStructWithJsonConverterAttribute()
    {
        const string TEST_SOURCE = """
            using TwitchySharp.Helpers;
            using System.Text.Json.Serialization;

            namespace TestNamespace;
            /// <summary>Test type</summary>
            [JsonConverter(typeof(FakeConverter<TestWrapper>))]
            public partial struct TestWrapper : IWrapValue<string>;
            """;

        const string EXPECTED_GENERATED_SOURCE = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial struct TestWrapper
            {
                public required string Value { get; init; }
                public static implicit operator string(TestWrapper wrapper) => wrapper.Value;
                public override global::System.String ToString() => Value?.ToString() ?? global::System.String.Empty;
            }

            """;

        CSharpSourceGeneratorTest<ValueWrapperMethodGenerator, DefaultVerifier> test = CreateGeneratorTest(TEST_SOURCE);
        test.TestState.GeneratedSources.Add((typeof(ValueWrapperMethodGenerator), "TestWrapper_ConversionMethods.g.cs", EXPECTED_GENERATED_SOURCE));

        await test.RunAsync(TestContext.Current.CancellationToken);
    }
}
